baseURL = 'https://redmine-japan.org/'
languageCode = 'ja'
title = 'Redmine Japan - Redmine Japan Vol.3'
theme = 'redmine-japan'
relativeurls = true

[params]
  description = 'Redmine Japan Vol.3'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
