baseURL = 'https://redmine-japan.org/'
languageCode = 'ja'
title = 'Redmine Japan'
copyright = 'Copyright © Redmine Japan Vol.3. All rights reserved'

theme = 'redmine-japan'
relativeurls = true

[menu]
[[menu.main]]
  name = '基調講演'
  url  = '/#speakers'
  weight = 1
[[menu.main]]
  name = 'ACCESS'
  url  = '/#access'
  weight = 2
[[menu.main]]
  name = 'スポンサー'
  url  = '/#sponsors'
  weight = 3
[[menu.main]]
  name = 'アンチハラスメントポリシー'
  url  = '/policies'
  weight = 4
[[menu.main]]
  name = 'お問い合わせ'
  url  = '/#contact'
  weight = 5

[params]
  subtitle = 'Redmine Japan Vol.3'
  description = 'Redmine Japanは、 オープンソースの無料利用できるプロジェクト管理ツール 『Redmine』に関するカンファレンスイベントになります。'

  google_site_verification = 'La2iUx1CTFy4uu_z1s_CEWkHB9JuL4owdPQOJe2BreU'
  googletagmanager_id = 'UA-45901614-10'
  googleads_id = '10840485180'
  conversion   = '718dCOSIkZEDELzakrEo'


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
    [markup.goldmark.parser.attribute]
      block = true
